language: node_js
node_js: stable
install:
  - npm install
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "taotaoliu"
  - git config user.email "1007829260@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - Blog
env:
 global:
   - GH_REF: github.com/taotaoliu/taotaoliu.github.io.git