language: node_js
node_js: stable
install:
  - npm install
script:
  - hexo g
after_script:
  - hexo deploy
  
branches:
  only:
    - Blog
env:
 global:
   - GH_REF: github.com/taotaoliu/taotaoliu.github.io.git